language: cpp

# Build matrix
os:
- linux
- osx
env:
  matrix:
  - NODE_VERSION="8"
  - NODE_VERSION="10"
  - NODE_VERSION="8" npm_config_runtime="electron" npm_config_target="2.0.6" npm_config_disturl="https://atom.io/download/electron"
  - NODE_VERSION="10" npm_config_runtime="electron" npm_config_target="4.0.1" npm_config_disturl="https://atom.io/download/electron"

before_install:
- uname -a
- nvm install $NODE_VERSION
- node --version
- node -p 'process.platform + "@" + process.arch'
- npm --version

install:
- export PATH=./node_modules/.bin/:$PATH
- npm install -g node-pre-gyp-github@1.3.1

script:
- npm install --build-from-source
- "./node_modules/.bin/node-pre-gyp package"
- echo $TRAVIS_TAG
# - echo $TRAVIS_PULL_REQUEST
# - |
#     if [[ "$TRAVIS_TAG" =~ ^v?[0-9] ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
#       node-pre-gyp-github publish
#     fi
