branches:
  only:
    - master
    - /^v?[0-9]/

language: cpp

filter_secrets: false

os:
- linux
- osx
- windows

env:
  global:
  - NODE_ARCH="64"
  matrix:
  - NODE_VERSION="8.15.0"
  - NODE_VERSION="10.15.0"
  - NODE_VERSION="11.7.0"
  - NODE_VERSION="8.15.0" npm_config_runtime="electron" npm_config_target="2.0.6" npm_config_disturl="https://atom.io/download/electron"
  - NODE_VERSION="10.15.0" npm_config_runtime="electron" npm_config_target="4.0.1" npm_config_disturl="https://atom.io/download/electron"

matrix:
  include:
  - os: windows
    env: NODE_ARCH="32" NODE_VERSION="8.15.0"
  - os: windows
    env: NODE_ARCH="32" NODE_VERSION="10.15.0"
  - os: windows
    env: NODE_ARCH="32" NODE_VERSION="11.7.0"
  - os: windows
    env: NODE_ARCH="32" NODE_VERSION="8.15.0" npm_config_runtime="electron" npm_config_target="2.0.6" npm_config_disturl="https://atom.io/download/electron"
  - os: windows
    env: NODE_ARCH="32" NODE_VERSION="10.15.0" npm_config_runtime="electron" npm_config_target="4.0.1" npm_config_disturl="https://atom.io/download/electron"

before_install:
- |
  if [ $TRAVIS_OS_NAME == "linux" ]; then
    sudo apt-get install -y libudev-dev
  fi
- |
  if [ $TRAVIS_OS_NAME == "windows" ]; then
    choco install -y nvm
    export NVM_HOME="C:\ProgramData\nvm"
    export NVM_SYMLINK="C:\Program Files\nodejs"
    export PATH=$PATH:$NVM_HOME:$NVM_SYMLINK
    nvm install $NODE_VERSION $NODE_ARCH
    nvm use $NODE_VERSION $NODE_ARCH
  else
    nvm install $NODE_VERSION
    nvm use $NODE_VERSION
  fi

script:
- npm install --build-from-source
- ./node_modules/.bin/node-pre-gyp package
- echo $TRAVIS_TAG
- echo $TRAVIS_PULL_REQUEST
- |
    if [[ "$TRAVIS_TAG" =~ ^v?[0-9] ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      npm install node-pre-gyp-github@1.4.3
      ./node_modules/.bin/node-pre-gyp-github publish
    fi
